assignment_part_sid:
  name: "BerkeleyX-cs169x" Matches the queuename entered on edX
  type: GraderType should be in lib/graders
  due:  yyyymmddhhmmss
  grace_period: grace period in days, used for latescaling/ currently disabled to handle multiple iterations using the
                same queue
  parts: #name of assignment, this gets sent in the submission payload
    assign-1-part-1:
      uri: Path to solution, from the base rag directory eg: ./solutions/....
      type: HW5Grader