live:
  queue_uri: 'uri'
  autograders_yml: ./config/autograders.yml
  django_auth:
    username: 'username'
    password: 'password'
  user_auth: #may be unnecessary
    user_name: 'username' 
    user_pass: 'password'
  halt: false # default: true, exit when all submission queues are empty
  sleep_duration: 30 # default 300, time in seconds to sleep when all queues are empty, only valid when halt == false doesn't matter yet